Fix calculate button not working after edit
vtex-apps/shipping-calculator pull request #28
Opened 2020-02-12 20:09 UTC by lucasecdb

#### What problem is this solving?
Sometimes, when you clicked to edit the zipcode and didn't edit the value in the input, the "calculate" button wouldn't do anything when pressed.

[Clubhouse story](https://app.clubhouse.io/vtex/story/27287/corrigir-erro-ao-clicar-em-alterar-cep-e-manter-o-mesmo-valor-para-c%C3%A1lculo-das-op%C3%A7%C3%B5es).

#### How should this be manually tested?
[Workspace](https://lucas--checkoutio.myvtex.com/cart)

#### Checklist/Reminders

- [ ] Updated `README.md`.
- [x] Updated `CHANGELOG.md`.
- [x] Linked this PR to a Clubhouse story (if applicable).
- [ ] Updated/created tests (important for bug fixes).
- [ ] Deleted the workspace after merging this PR (if applicable).

#### Type of changes

✔️ | Type of Change
---|---
✔️ | Bug fix 
_ | New feature 
_ | Breaking change 
_ | Technical improvements

2020-02-12 20:48 UTC, jeffersontuc approved these changes

2020-02-12 20:50 UTC, jeffersontuc requested changes
I just tested, but I couldn't make it work.

2020-02-12 21:00 UTC, jeffersontuc commented
It worked. Nice job! 👍

2020-02-12 21:01 UTC, jeffersontuc approved these changes

2020-02-14 19:58 UTC, marcoskwkm approved these changes

2020-02-17 12:53 UTC, merged